### ISSUE TITLE
error

### ISSUE THREAD

**Issue by ENDERM4NQ** [hendrikbgr/TikTok-Account-Creator#5]
Traceback (most recent call last):
  File "C:\Users\Kacper\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\Kacper\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Kacper\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "run.py", line 52, in <module>
    webdriver = webdriver.Firefox(executable_path="./geckodriver", firefox_profile=profile)
  File "C:\Users\Kacper\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\firefox\webdriver.py", line 164, in __init__
    self.service.start()
  File "C:\Users\Kacper\AppData\Local\Programs\Python\Python38\lib\site-packages\selenium\webdriver\common\service.py", line 86, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable may have wrong permissions.

**Comment by bahaamezher3** [comment]
try not using sudo because if u are using it u need --sandbox extention

**Comment by vqoley** [comment]
> try not using sudo because if u are using it u need --sandbox extention

this script still working?
